Feature: detection of new accounts and of account movements
As a system administrator,
I flow all events related to managed accounts to a single event bus
so as to build an event-driven architecture for the personal accounts that I manage

Scenario: where a new account is detected
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When an AWS account is created into this AWS Organisation
Then the native event generated by 'aws:organizations' is pushed to the event bus
# implementation: event is detected at root level, and injected into the event bus of account 'Automation'

Scenario: where the move of an account is detected
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When an AWS account is moved from one OU to another OU into this AWS Organisation
Then the native event generated by 'aws:organizations' is pushed to the event bus
# implementation: event is detected at root level, and injected into the event bus of account 'Automation'

Scenario: where vanilla account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When lambda function 'MoveVanillaAccount' is executed
Then lambda function emits an event 'VanillaAccount' on event bus
# implementation: lambda function is ran within account 'Automation', and emits event there

Scenario: where assigned account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When lambda function 'SignalAssignedAccount' is executed
Then lambda function emits event 'AssignedAccount' on event bus
# implementation: lambda function is ran within account 'Automation', and emits event there

Scenario: where prepared account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When codebuild project 'PrepareAccount' is executed within assigned account
Then codebuild project emits an event 'PreparedAccount' on event bus when job has been completed
# implementation: codebuild project is ran within target account, and emits event across accounts
# note: default event bus of account 'Automation' should accept events from entire AWS Organisation

Scenario: where released account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When lambda function 'MoveAssignedAccount' is executed
Then lambda function emits an event 'ReleasedAccount' on event bus
# implementation: lambda function is ran within account 'Automation', and emits event there

Scenario: where expired account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When lambda function 'SignalExpiredAccount' is executed
Then lambda function emits an event 'ExpiredAccount' on event bus
# implementation: lambda function is ran within account 'Automation', and emits event there

Scenario: where purged account is reported
Given the default event bus of AWS account 'Automation' in an AWS Organisation
When codebuild project 'PurgeAccount' is executed within assigned account
Then codebuild project emits an event 'PurgedAccount' on event bus when job has been completed
# implementation: codebuild project is ran within target account, and emits event across accounts
# note: default event bus of account 'Automation' should accept events from entire AWS Organisation
