Feature: consolidation of events across accounts into a single event bus

    As a system administrator,
    I flow all events related to managed accounts to a single event bus
    so as to build an event-driven architecture for the personal accounts that I manage

    As a system administrator,
    I ship events from codebuild projects ran on managed accounts to a single event bus
    so as to build an event-driven architecture for the personal accounts that I manage

    Scenario: where a new account is detected
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When an AWS account is created into this AWS Organisation
        Then the native event generated by 'aws:organizations' is pushed to the event bus of management account
        And the event is forwarded to the event bus of account 'Automation'

    Scenario: where the move of an account is detected
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When an AWS account is moved from one OU to another OU into this AWS Organisation
        Then the native event generated by 'aws:organizations' is pushed to the event bus of management account
        And the event is forwarded to the event bus of account 'Automation'

    Scenario: where the tagging of an account is detected
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When an AWS account is tagged
        Then the native event generated by 'aws:organizations' is pushed to the event bus of management account
        And the event is forwarded to the event bus of account 'Automation'

    Scenario: where the execution of CodeBuild project is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When CodeBuild project is executed within assigned account
        Then the native event generated by 'aws:codebuild' is pushed to the event bus of running account
        And the event is forwarded to the event bus of account 'Automation'

    Scenario: where vanilla account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnVanillaAccount' is executed
        Then lambda function emits an event 'VanillaAccount' on event bus of account 'Automation'

    Scenario: where assigned account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnAssignedAccount' is executed
        Then lambda function emits event 'AssignedAccount' on event bus of account 'Automation'

    Scenario: where outcome of the CodeBuild preparation project is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When the CodeBuild project 'preparation' is ran on an AWS account into this AWS Organisation
        Then CodeBuild code emits event 'PreparationReport' on event bus of account 'Automation'

    Scenario: where prepared account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnPreparedAccount' is executed
        Then lambda function emits event 'PreparedAccount' on event bus of account 'Automation'

    Scenario: where released account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnReleasedAccount' is executed
        Then lambda function emits an event 'ReleasedAccount' on event bus on account 'Automation'

    Scenario: where expired account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnExpiredAccount' is executed
        Then lambda function emits an event 'ExpiredAccount' on event bus on account 'Automation'

    Scenario: where outcome of the CodeBuild purge project is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When the CodeBuild project 'purge' is ran on an AWS account into this AWS Organisation
        Then CodeBuild code emits event 'PurgeReport' on event bus of running account
        And the event is forwarded to the event bus of account 'Automation'

    Scenario: where purged account is reported
        Given the default event bus of AWS account 'Automation' in an AWS Organisation
        When lambda function 'OnPurgedAccount' is executed
        Then lambda function emits an event 'PurgedAccount' on event bus of account 'Automation'

